<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0FAJM8M" failures="1" tests="3" name="Surefire test" time="0.043" errors="0" timestamp="01 Apr 2018 11:21:07 GMT">
  <testcase classname="samples.SampleTest" name="first" time="0.008"/>
  <testcase classname="samples.SampleTest" name="second" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at samples.SampleTest.second(SampleTest.java:15)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase classname="samples.SampleTest" name="third" time="0.0"/>
</testsuite> <!-- Surefire test -->
