<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-0FAJM8M" failures="1" tests="2" name="test1" time="0.111" errors="0" timestamp="01 Apr 2018 11:50:15 GMT">
  <testcase classname="samples.SampleTest" name="first" time="0.008"/>
  <testcase classname="samples.SampleTest" name="second" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at samples.SampleTest.second(SampleTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase classname="samples.SampleTest" name="third" time="0.0">
    <ignored/>
  </testcase> <!-- third -->
</testsuite> <!-- test1 -->
